/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TerraLedger {
  export type LandRecordStruct = {
    id: BigNumberish;
    landId: string;
    ownerName: string;
    location: string;
    area: BigNumberish;
    registeredBy: AddressLike;
    currentOwner: AddressLike;
    isActive: boolean;
    documentHash: string;
  };

  export type LandRecordStructOutput = [
    id: bigint,
    landId: string,
    ownerName: string,
    location: string,
    area: bigint,
    registeredBy: string,
    currentOwner: string,
    isActive: boolean,
    documentHash: string
  ] & {
    id: bigint;
    landId: string;
    ownerName: string;
    location: string;
    area: bigint;
    registeredBy: string;
    currentOwner: string;
    isActive: boolean;
    documentHash: string;
  };
}

export interface TerraLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveTransfer"
      | "deactivateLand"
      | "getLand"
      | "getOwnershipHistory"
      | "initiateTransfer"
      | "ownershipHistory"
      | "recordCounter"
      | "records"
      | "registerLand"
      | "registrar"
      | "transferRegistrar"
      | "transferRequests"
      | "updateDocumentHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DocumentAttached"
      | "LandRegistered"
      | "OwnershipRecorded"
      | "TransferApproved"
      | "TransferInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateLand",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLand",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnershipHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownershipHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerLand",
    values: [string, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "registrar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDocumentHash",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateLand",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLand", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOwnershipHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownershipHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerLand",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registrar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDocumentHash",
    data: BytesLike
  ): Result;
}

export namespace DocumentAttachedEvent {
  export type InputTuple = [landId: BigNumberish, documentHash: string];
  export type OutputTuple = [landId: bigint, documentHash: string];
  export interface OutputObject {
    landId: bigint;
    documentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LandRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    landId: string,
    ownerName: string,
    registeredBy: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    landId: string,
    ownerName: string,
    registeredBy: string
  ];
  export interface OutputObject {
    id: bigint;
    landId: string;
    ownerName: string;
    registeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipRecordedEvent {
  export type InputTuple = [landId: BigNumberish, newOwner: AddressLike];
  export type OutputTuple = [landId: bigint, newOwner: string];
  export interface OutputObject {
    landId: bigint;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferApprovedEvent {
  export type InputTuple = [
    landId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [landId: bigint, from: string, to: string];
  export interface OutputObject {
    landId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    landId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [landId: bigint, from: string, to: string];
  export interface OutputObject {
    landId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TerraLedger extends BaseContract {
  connect(runner?: ContractRunner | null): TerraLedger;
  waitForDeployment(): Promise<this>;

  interface: TerraLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveTransfer: TypedContractMethod<
    [_landId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deactivateLand: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  getLand: TypedContractMethod<
    [_id: BigNumberish],
    [TerraLedger.LandRecordStructOutput],
    "view"
  >;

  getOwnershipHistory: TypedContractMethod<
    [_landId: BigNumberish],
    [string[]],
    "view"
  >;

  initiateTransfer: TypedContractMethod<
    [_landId: BigNumberish, _to: AddressLike],
    [void],
    "nonpayable"
  >;

  ownershipHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  recordCounter: TypedContractMethod<[], [bigint], "view">;

  records: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        boolean,
        string
      ] & {
        id: bigint;
        landId: string;
        ownerName: string;
        location: string;
        area: bigint;
        registeredBy: string;
        currentOwner: string;
        isActive: boolean;
        documentHash: string;
      }
    ],
    "view"
  >;

  registerLand: TypedContractMethod<
    [
      _landId: string,
      _ownerName: string,
      _location: string,
      _area: BigNumberish,
      _documentHash: string
    ],
    [void],
    "nonpayable"
  >;

  registrar: TypedContractMethod<[], [string], "view">;

  transferRegistrar: TypedContractMethod<
    [newRegistrar: AddressLike],
    [void],
    "nonpayable"
  >;

  transferRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean] & {
        landId: bigint;
        from: string;
        to: string;
        approved: boolean;
      }
    ],
    "view"
  >;

  updateDocumentHash: TypedContractMethod<
    [_landId: BigNumberish, _newHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveTransfer"
  ): TypedContractMethod<[_landId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateLand"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getLand"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [TerraLedger.LandRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnershipHistory"
  ): TypedContractMethod<[_landId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [_landId: BigNumberish, _to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ownershipHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        boolean,
        string
      ] & {
        id: bigint;
        landId: string;
        ownerName: string;
        location: string;
        area: bigint;
        registeredBy: string;
        currentOwner: string;
        isActive: boolean;
        documentHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerLand"
  ): TypedContractMethod<
    [
      _landId: string,
      _ownerName: string,
      _location: string,
      _area: BigNumberish,
      _documentHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registrar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferRegistrar"
  ): TypedContractMethod<[newRegistrar: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean] & {
        landId: bigint;
        from: string;
        to: string;
        approved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateDocumentHash"
  ): TypedContractMethod<
    [_landId: BigNumberish, _newHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DocumentAttached"
  ): TypedContractEvent<
    DocumentAttachedEvent.InputTuple,
    DocumentAttachedEvent.OutputTuple,
    DocumentAttachedEvent.OutputObject
  >;
  getEvent(
    key: "LandRegistered"
  ): TypedContractEvent<
    LandRegisteredEvent.InputTuple,
    LandRegisteredEvent.OutputTuple,
    LandRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipRecorded"
  ): TypedContractEvent<
    OwnershipRecordedEvent.InputTuple,
    OwnershipRecordedEvent.OutputTuple,
    OwnershipRecordedEvent.OutputObject
  >;
  getEvent(
    key: "TransferApproved"
  ): TypedContractEvent<
    TransferApprovedEvent.InputTuple,
    TransferApprovedEvent.OutputTuple,
    TransferApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;

  filters: {
    "DocumentAttached(uint256,string)": TypedContractEvent<
      DocumentAttachedEvent.InputTuple,
      DocumentAttachedEvent.OutputTuple,
      DocumentAttachedEvent.OutputObject
    >;
    DocumentAttached: TypedContractEvent<
      DocumentAttachedEvent.InputTuple,
      DocumentAttachedEvent.OutputTuple,
      DocumentAttachedEvent.OutputObject
    >;

    "LandRegistered(uint256,string,string,address)": TypedContractEvent<
      LandRegisteredEvent.InputTuple,
      LandRegisteredEvent.OutputTuple,
      LandRegisteredEvent.OutputObject
    >;
    LandRegistered: TypedContractEvent<
      LandRegisteredEvent.InputTuple,
      LandRegisteredEvent.OutputTuple,
      LandRegisteredEvent.OutputObject
    >;

    "OwnershipRecorded(uint256,address)": TypedContractEvent<
      OwnershipRecordedEvent.InputTuple,
      OwnershipRecordedEvent.OutputTuple,
      OwnershipRecordedEvent.OutputObject
    >;
    OwnershipRecorded: TypedContractEvent<
      OwnershipRecordedEvent.InputTuple,
      OwnershipRecordedEvent.OutputTuple,
      OwnershipRecordedEvent.OutputObject
    >;

    "TransferApproved(uint256,address,address)": TypedContractEvent<
      TransferApprovedEvent.InputTuple,
      TransferApprovedEvent.OutputTuple,
      TransferApprovedEvent.OutputObject
    >;
    TransferApproved: TypedContractEvent<
      TransferApprovedEvent.InputTuple,
      TransferApprovedEvent.OutputTuple,
      TransferApprovedEvent.OutputObject
    >;

    "TransferInitiated(uint256,address,address)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
  };
}
